registry:
  port: 8761
  idcI:
    default: localhost
    repI: 192.168.0.109
    repII: 192.168.0.108
    repIII: 192.168.0.111
    repIV: 192.168.0.115
server:
  port: 8763
spring:
  application:
    name: user-test
info:
  app:
    name: '@project.artifactId@'
    encoding: '@project.build.sourceEncoding@'
    java: '@java.version@'
management:
  security:
    enabled: false
eureka:
  instance:
    hostname: localhost
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
    instance-id: ${spring.cloud.client.ipAddress}:${spring.application.name}:${server.port}
  client:
    healthcheck:
      enabled: true
#    region: idc
#    availabilityZones: 
#      idc: idcI,idcII,idcIII
    serviceUrl:
#      defaultZone: http://${registry.idcI.default}:${registry.port}/eureka/ 
      defaultZone: http://${registry.idcI.repI}:${registry.port}/eureka/,http://${registry.idcI.repII}:${registry.port}/eureka/,http://${registry.idcI.repIII}:${registry.port}/eureka/,http://${registry.idcI.repIV}:${registry.port}/eureka/
#      idcII: http://${registry.idcII}:${registry.port}/eureka/,http://${registry.idcI}:${registry.port}/eureka/,http://${registry.idcI}:${registry.port}/eureka/
#      idcIII: http://${registry.idcIII}:${registry.port}/eureka/,http://${registry.idcI}:${registry.port}/eureka/,http://${registry.idcI}:${registry.port}/eureka/